# Generated by Django 3.2.2 on 2021-05-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('file_number', 'hospital'), name='unique_file-number_hospital'),
        ),
    ]
