# Generated by Django 3.2.2 on 2021-05-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_helper', '0002_patient_unique_file-number_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ct_helper.hospital'),
        ),
    ]
