# Generated by Django 3.2.2 on 2021-05-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct_helper', '0003_operation_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='order',
        ),
    ]
