# Generated by Django 3.2.2 on 2021-05-31 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_helper', '0004_remove_prescription_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drug',
            name='unique_drug_name',
        ),
        migrations.RemoveConstraint(
            model_name='hospital',
            name='unique_hospital_name',
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_patient_hospital',
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_file-number_hospital',
        ),
        migrations.RemoveConstraint(
            model_name='surgeon',
            name='unique_surgeon_name',
        ),
        migrations.AlterField(
            model_name='test',
            name='aLT',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 300.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(300.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='aST',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 300.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(300.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='creatine',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.0 - 30.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(30.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='gFR',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 200.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='hBA1C',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.0 - 20.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(20.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='hDL',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 1000.0', max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(1000.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='hP',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.0 - 20.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(20.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='k',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 200.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='lDL',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 1000.0', max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(1000.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='nA',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 200.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='platelt',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 500.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(500.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='t3',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 1000.0', max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(1000.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='t4',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 1000.0', max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(1000.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='tSH',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 1000.0', max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(1000.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='urea',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 200.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='wBC',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0 - 700.0', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(700.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.UniqueConstraint(fields=('drug_name', 'owner'), name='unique_drug_name'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.UniqueConstraint(fields=('hospital_name', 'owner'), name='unique_hospital_name'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('patient_name', 'hospital', 'owner'), name='unique_patient_hospital'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('file_number', 'hospital', 'owner'), name='unique_file-number_hospital'),
        ),
        migrations.AddConstraint(
            model_name='surgeon',
            constraint=models.UniqueConstraint(fields=('surgeon_name', 'owner'), name='unique_surgeon_name'),
        ),
    ]
