# Generated by Django 3.2.2 on 2021-06-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct_helper', '0006_auto_20210601_0340'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hospital',
            name='unique_hospital_website',
        ),
        migrations.RemoveConstraint(
            model_name='hospital',
            name='unique_hospital_phone_number',
        ),
        migrations.RemoveConstraint(
            model_name='surgeon',
            name='unique_surgeon_Email',
        ),
        migrations.RemoveConstraint(
            model_name='surgeon',
            name='unique_surgeon_phone_number',
        ),
    ]
